# Generated by Django 5.2.17 on 2026-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_idade_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
    ]
