# Generated by Django 5.2.17 on 2026-08-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
    ]
